# Generated by Django 4.2.6 on 2023-10-08 17:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 100 символов', max_length=150, verbose_name='Название')),
                ('named_url', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Выберете пункт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.menumodel', verbose_name='Выберете поле')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
