# Generated by Django 4.2.6 on 2023-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='name',
            field=models.CharField(help_text='Максимум 100 символов', max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
